

POST http://localhost:5187/enderecos/cadastrar  
Content-Type: application/json

{     
    "Logradouro": "R.Filadelfia",     
    "Cidade": "Colombo",     
    "Uf": "PR",     
    "Cep": "83430-830",     
    "Numero": "334" 
} 


###
GET http://localhost:5187/abrigos/listar  


###
GET http://localhost:5187/abrigos/buscar-por-cidade/curitiba  


###
POST http://localhost:5187/abrigos/cadastrar  
Content-Type: application/json

{   
    "Nome": "Adocão",      
    "QtdPets": 10,     
    "EnderecoId": 7 
} 


###
DELETE http://localhost:5187/abrigos/excluir/6  


###
POST http://localhost:5187/pets/cadastrar  
Content-Type: application/json

{     
    "Nome": "Bobão",     
    "Idade": "1",     
    "UnidadeTempo": "anos",    
    "Porte": "P",     
    "Descricao": "Agitado e Brabo",     
    "AbrigoId": 6  
 } 


###
GET http://localhost:5187/pets/listar 
 
###
PUT http://localhost:5187/pets/alterar/7  
Content-Type: application/json

 {
    "petId": 7,     
    "Nome": "Bobão",     
    "Idade": "1",     
    "UnidadeTempo": "anos",    
    "Porte": "P",     
    "Descricao": "Brincalhão e Calmo",     
    "AbrigoId": 1  
  } 
 

###
DELETE http://localhost:5187/pets/excluir/5  

###
GET http://localhost:5187/pets/buscar-por-abrigo/Abrigo amigo animal  



###
POST http://localhost:5187/adocoes/cadastrar  
Content-Type: application/json
 
{     
    "AbrigoId": "1",     
    "PetId": "7",     
    "cpfTutor": "085.757.489-21"  
} 


###
GET http://localhost:5187/adocoes/listar