

POST http://localhost:5187/enderecos/cadastrar  
Content-Type: application/json

{     
    "Logradouro": "R.Mirador",     
    "Cidade": "Colombo",     
    "Uf": "PR",     
    "Cep": "83410-810",     
    "Numero": "387" 
} 


###
GET http://localhost:5187/abrigos/listar  


###
GET http://localhost:5187/abrigos/buscar-por-cidade/curitiba  


###
POST http://localhost:5187/abrigos/cadastrar  
Content-Type: application/json

{   
    "Nome": "Abrigo Dog Feliz",      
    "QtdPets": 10,     
    "EnderecoId": 5  
} 


###
DELETE http://localhost:5187/abrigos/excluir/2  


###
POST http://localhost:5187/pets/cadastrar  
Content-Type: application/json

{     
    "Nome": "Panqueca",     
    "Idade": "1",     
    "UnidadeTempo": "anos",    
    "Porte": "P",     
    "Descricao": "Preguiçosa e carinhosa",     
    "AbrigoId": 3  
 } 


###
GET http://localhost:5187/pets/listar 
 
###
PUT http://localhost:5187/pets/alterar/4  
Content-Type: application/json

 {
    "petId": 4,     
    "Nome": "Panqueca",     
    "Idade": "1",     
    "UnidadeTempo": "anos",    
    "Porte": "G",     
    "Descricao": "Brincalhona e raivosa",     
    "AbrigoId": 1  
  } 
 

###
DELETE http://localhost:5187/pets/excluir/4  

###
GET http://localhost:5187/pets/buscar-por-abrigo/Abrigo amigo animal  



###
POST http://localhost:5187/adocoes/cadastrar  
Content-Type: application/json
 
{     
    "AbrigoId": "1",     
    "PetId": "3",     
    "cpfTutor": "094.357.839-61"  
} 


###
GET http://localhost:5187/adocoes/listar